### ISSUE TITLE
Game not ends

### ISSUE THREAD

**Issue by Masynchin** [cpcloud/minesweep-rs#1051]
Just played your game in Docker and did this:

<img width="640" alt="Game field, all non-bombs cells opened, bombs cells not marked" src="https://github.com/cpcloud/minesweep-rs/assets/47028153/5409c5f1-8645-42a2-90ed-a5e29803ef1a">

It should end, doesn't it?

**Comment by cpcloud** [comment]
Yeah, seems like an end state! Not sure what the issue is off the top of my head, but thanks for the report!

**Comment by Masynchin** [comment]
> Not sure what the issue is off the top of my head

Probably this check, which assumes bombs should be flagged:

https://github.com/cpcloud/minesweep-rs/blob/136baa06f2baf63e2c071169efd83fd75e3ea000/src/sweep.rs#L123-L128

I dealt with it in my minesweeper implementation too. The answer would probably be to check if amount of covered cells equals to amount of bombs.
